"""
Comprehensive All-India Real Estate Benchmark Dataset
Extensive Coverage of:
1. NAGPUR: Main City + Outer Belt (Wardha Rd, MIHAN, Butibori, Hingna, Besa-Pipla, Wadi, Koradi, Kamptee, Umred Rd)
2. PUNE: Main City + Outer Belt (Hinjewadi 1-4, Baner, Wakad, Ravet, Moshi, Chakan, Kharadi, Wagholi, Magarpatta, Undri, Bavdhan, Pirangut)
3. MUMBAI MMR: Main City + Outer Belt (South Mumbai, Western Suburbs, Central, Thane, Navi Mumbai, Kalyan-Dombivli, Mira-Bhayandar, Vasai-Virar, Palghar, Badlapur, Karjat, Alibaug)
4. Major Indian Metros: Bangalore, Delhi NCR, Hyderabad, Chennai, Ahmedabad, GIFT City, Kolkata, Goa, Chandigarh, Jaipur, Lucknow, Indore, etc.

Multi-Property Types:
- Flats / High-Rise Apartments (1, 2, 3, 4 BHK)
- Residential NA / Sanctioned Plots (Sq.ft & Guntha rates; 1 Guntha = 1,089 sq.ft)
- Duplex & Triplex Penthouses
- Independent Homes, Row Houses & Luxury Villas
"""

STATE_STAMP_DUTY = {
    "Maharashtra": {
        "stamp_duty_male": 6.0,  # 5% base + 1% metro cess/LBT
        "stamp_duty_female": 5.0, # 1% concession for female buyers
        "registration_fee_percent": 1.0,
        "registration_fee_cap": 30000, # Max ₹30,000 cap in Maharashtra
        "authority": "Inspector General of Registration (IGR Maharashtra)",
        "rera_portal": "MahaRERA (maharera.mahaonline.gov.in)",
        "planning_authorities": ["MMRDA (Mumbai)", "CIDCO (Navi Mumbai)", "PMRDA (Pune)", "PCMC (Pimpri-Chinchwad)", "NMRDA / NIT (Nagpur)"]
    },
    "Karnataka": {
        "stamp_duty_male": 5.0,
        "stamp_duty_female": 5.0,
        "registration_fee_percent": 1.0,
        "registration_fee_cap": None,
        "authority": "Department of Stamps and Registration (Kaveri Portal, Karnataka)",
        "rera_portal": "Karnataka RERA (rera.karnataka.gov.in)",
        "planning_authorities": ["BBMP", "BDA", "BMRDA"]
    },
    "Delhi": {
        "stamp_duty_male": 6.0,
        "stamp_duty_female": 4.0,
        "registration_fee_percent": 1.0,
        "registration_fee_cap": None,
        "authority": "Revenue Department, Government of NCT of Delhi (DORIS)",
        "rera_portal": "Delhi RERA (rera.delhi.gov.in)",
        "planning_authorities": ["DDA", "MCD"]
    },
    "Haryana": {
        "stamp_duty_male": 7.0,
        "stamp_duty_female": 5.0,
        "registration_fee_percent": 1.0,
        "registration_fee_cap": 50000,
        "authority": "Department of Revenue & Disaster Management, Haryana (Jamabandi)",
        "rera_portal": "HARERA (haryanarera.gov.in)",
        "planning_authorities": ["GMDA (Gurgaon)", "HSVP / HUDA", "DTCP Haryana"]
    },
    "Uttar Pradesh": {
        "stamp_duty_male": 7.0,
        "stamp_duty_female": 6.0,
        "registration_fee_percent": 1.0,
        "registration_fee_cap": None,
        "authority": "Stamp and Registration Department, UP (IGRSUP)",
        "rera_portal": "UP RERA (up-rera.in)",
        "planning_authorities": ["NOIDA Authority", "Greater Noida Authority (GNIDA)", "YEIDA", "LDA (Lucknow)"]
    },
    "Telangana": {
        "stamp_duty_male": 6.0,
        "stamp_duty_female": 6.0,
        "registration_fee_percent": 0.5,
        "registration_fee_cap": None,
        "authority": "Registration & Stamps Department, Telangana (Dharani Portal)",
        "rera_portal": "TSRERA (rera.telangana.gov.in)",
        "planning_authorities": ["HMDA", "GHMC"]
    },
    "Gujarat": {
        "stamp_duty_male": 4.9,
        "stamp_duty_female": 4.9,
        "registration_fee_percent": 1.0,
        "registration_fee_cap": None,
        "authority": "Superintendent of Stamps, Gujarat (Garvi)",
        "rera_portal": "GujRERA (gujrera.gujarat.gov.in)",
        "planning_authorities": ["AUDA (Ahmedabad)", "GIFT City Authority", "GUDA (Gandhinagar)", "SUDA (Surat)"]
    },
    "Default": {
        "stamp_duty_male": 6.0,
        "stamp_duty_female": 5.5,
        "registration_fee_percent": 1.0,
        "registration_fee_cap": 30000,
        "authority": "State Revenue & Stamp Registration Department",
        "rera_portal": "State Real Estate Regulatory Authority (RERA)",
        "planning_authorities": ["Municipal Corporation & Urban Development Authority"]
    }
}

ALL_INDIA_LOCALITIES = [
    # =========================================================================
    # NAGPUR: MAIN CITY + EXTENSIVE OUTER / CONNECTED SUBURBS & INDUSTRIAL
    # =========================================================================
    {
        "locality": "Dharampeth, Ramdaspeth & Shankar Nagar",
        "city": "Nagpur",
        "state": "Maharashtra",
        "zone": "Nagpur Core West",
        "category": "Main City",
        "circle_rate": 6500,
        "circle_rate_plot": 4800,
        "market_rate_min": 7800,
        "market_rate_max": 14500,
        "market_rate_avg": 10500,
        "plot_rate_sqft": 8200,
        "plot_rate_guntha": 8929800, # ~₹89.3L per Guntha (1 Guntha = 1089 sqft)
        "duplex_avg_price": 18500000, # ₹1.85 Cr
        "villa_avg_price": 28000000, # ₹2.80 Cr
        "rental_yield": 3.8,
        "cagr_5y": 9.2,
        "infra_score": 9.3,
        "livability_score": 9.4,
        "lat": 21.1415,
        "lng": 79.0620,
        "sanction_authority": "NMC / NIT",
        "notable_projects": ["Kukreja Infinity", "Rachana Yashashree", "Sandesh Heights"],
        "nhb_hpi_trend": "High Net Worth Hub (QoQ +2.4%)",
        "connectivity": "Nagpur Metro Aqua Line (Shankar Nagar Square), West High Court (WHC) Road",
        "tags": ["Posh Nagpur", "Medical & Legal Hub", "High Street Shopping", "Luxury Duplexes"]
    },
    {
        "locality": "Civil Lines & Sitabuldi",
        "city": "Nagpur",
        "state": "Maharashtra",
        "zone": "Nagpur Central",
        "category": "Main City",
        "circle_rate": 6200,
        "circle_rate_plot": 4500,
        "market_rate_min": 7200,
        "market_rate_max": 13800,
        "market_rate_avg": 9800,
        "plot_rate_sqft": 7500,
        "plot_rate_guntha": 8167500,
        "duplex_avg_price": 16500000,
        "villa_avg_price": 25000000,
        "rental_yield": 3.9,
        "cagr_5y": 8.7,
        "infra_score": 9.4,
        "livability_score": 9.5,
        "lat": 21.1524,
        "lng": 79.0734,
        "sanction_authority": "NMC / NIT",
        "notable_projects": ["Grace Landmark", "Sadoday Signature", "Nanded City Nagpur Enclave"],
        "nhb_hpi_trend": "Administrative Capital (QoQ +2.1%)",
        "connectivity": "Nagpur Metro Interchange (Sitabuldi Interchange), Nagpur Railway Station",
        "tags": ["High Court", "Vidhan Bhavan", "Green Canopy", "Commercial Interchange"]
    },
    {
        "locality": "Wardha Road, Somalwada & Chinchbhavan",
        "city": "Nagpur",
        "state": "Maharashtra",
        "zone": "Nagpur South",
        "category": "Main City / Inner Corridor",
        "circle_rate": 4500,
        "circle_rate_plot": 3200,
        "market_rate_min": 5200,
        "market_rate_max": 9500,
        "market_rate_avg": 6900,
        "plot_rate_sqft": 5200,
        "plot_rate_guntha": 5662800,
        "duplex_avg_price": 11500000,
        "villa_avg_price": 17500000,
        "rental_yield": 4.5,
        "cagr_5y": 12.1,
        "infra_score": 9.2,
        "livability_score": 9.0,
        "lat": 21.0967,
        "lng": 79.0664,
        "sanction_authority": "NMC / NMRDA",
        "notable_projects": ["Empress City Wardha Rd", "Narendra Nagar Elite", "First City Axis"],
        "nhb_hpi_trend": "Fastest Growing Corridor (QoQ +3.8%)",
        "connectivity": "Nagpur Metro Orange Line (Airport & Chhatrapati Square Stations), National Highway 44",
        "tags": ["Airport Proximity", "Orange Line Metro", "High Rental Liquidity"]
    },
    {
        "locality": "Manish Nagar, Besa, Pipla & Shankarpur",
        "city": "Nagpur",
        "state": "Maharashtra",
        "zone": "Nagpur South-East",
        "category": "Outer City Suburb",
        "circle_rate": 3800,
        "circle_rate_plot": 2600,
        "market_rate_min": 4400,
        "market_rate_max": 7800,
        "market_rate_avg": 5800,
        "plot_rate_sqft": 3800,
        "plot_rate_guntha": 4138200, # ~₹41.4L per Guntha
        "duplex_avg_price": 8500000,  # ₹85 Lakhs
        "villa_avg_price": 13500000, # ₹1.35 Cr
        "rental_yield": 4.8,
        "cagr_5y": 13.5,
        "infra_score": 8.9,
        "livability_score": 8.8,
        "lat": 21.0820,
        "lng": 79.0833,
        "sanction_authority": "NMRDA (RL Sanctioned)",
        "notable_projects": ["Besa Green City", "Pipla Palm Greens", "Manish Nagar Enclaves", "Radhe Krishna Township"],
        "nhb_hpi_trend": "Residential Boom (QoQ +4.2%)",
        "connectivity": "Manish Nagar Railway Underbridge (RUB), Outer Ring Road, 10 mins to Airport",
        "tags": ["Hotspot for NMRDA Plots", "Gated Duplex Townships", "Young IT Families"]
    },
    {
        "locality": "MIHAN SEZ, Khapri & Butibori MIDC Axis",
        "city": "Nagpur",
        "state": "Maharashtra",
        "zone": "Nagpur South Outer",
        "category": "Outer Industrial & SEZ Corridor",
        "circle_rate": 2800,
        "circle_rate_plot": 1800,
        "market_rate_min": 3400,
        "market_rate_max": 6800,
        "market_rate_avg": 4600,
        "plot_rate_sqft": 2400,
        "plot_rate_guntha": 2613600, # ~₹26.1L per Guntha
        "duplex_avg_price": 6500000,  # ₹65 Lakhs
        "villa_avg_price": 9800000,  # ₹98 Lakhs
        "rental_yield": 5.1,
        "cagr_5y": 15.2,
        "infra_score": 9.1,
        "livability_score": 8.4,
        "lat": 20.9850,
        "lng": 79.0300,
        "sanction_authority": "NMRDA / MADC / MIDC",
        "notable_projects": ["Mahindra Bloomdale", "First City MIHAN", "Shiv Kailasa", "Moraj Waterfall Gateway"],
        "nhb_hpi_trend": "Supercharged SEZ Growth (QoQ +4.8%)",
        "connectivity": "Nagpur Metro Orange Line (Khapri & Metro City), Samruddhi Mahamarg Highway, AIIMS Nagpur, IIM Nagpur",
        "tags": ["Samruddhi Expressway", "AIIMS Nagpur", "Boeing / TCS / Infosys SEZ", "Butibori Industrial Corridor"]
    },
    {
        "locality": "Hingna Road, Wanadongri & Digdoh MIDC",
        "city": "Nagpur",
        "state": "Maharashtra",
        "zone": "Nagpur South-West Outer",
        "category": "Outer Educational & Industrial Hub",
        "circle_rate": 3200,
        "circle_rate_plot": 2100,
        "market_rate_min": 3600,
        "market_rate_max": 6400,
        "market_rate_avg": 4700,
        "plot_rate_sqft": 2600,
        "plot_rate_guntha": 2831400,
        "duplex_avg_price": 6800000,
        "villa_avg_price": 10500000,
        "rental_yield": 4.6,
        "cagr_5y": 11.2,
        "infra_score": 8.6,
        "livability_score": 8.3,
        "lat": 21.1022,
        "lng": 78.9920,
        "sanction_authority": "NMRDA / MIDC",
        "notable_projects": ["Hingna Greens", "Lata Mangeshkar Hospital Enclave", "Raisoni City"],
        "nhb_hpi_trend": "Steady Student & Industrial Demand (QoQ +2.8%)",
        "connectivity": "Nagpur Metro Aqua Line (Lokmanya Nagar Terminal), Hingna MIDC Main Road",
        "tags": ["Aqua Line Metro Terminal", "Engineering & Medical Colleges", "Affordable Plots"]
    },
    {
        "locality": "Wadi, Dattawadi & Gondkhairi (Amravati Road)",
        "city": "Nagpur",
        "state": "Maharashtra",
        "zone": "Nagpur West Outer",
        "category": "Outer Logistics & Growth Corridor",
        "circle_rate": 2600,
        "circle_rate_plot": 1600,
        "market_rate_min": 3100,
        "market_rate_max": 5400,
        "market_rate_avg": 3900,
        "plot_rate_sqft": 1950,
        "plot_rate_guntha": 2123550,
        "duplex_avg_price": 5500000,
        "villa_avg_price": 8500000,
        "rental_yield": 4.2,
        "cagr_5y": 12.8,
        "infra_score": 8.4,
        "livability_score": 8.1,
        "lat": 21.1550,
        "lng": 78.9680,
        "sanction_authority": "NMRDA / NHAI",
        "notable_projects": ["Amravati Road Royal City", "Wadi Smart Enclaves", "Gondkhairi Samruddhi Plots"],
        "nhb_hpi_trend": "Samruddhi Mahamarg Feeder (QoQ +3.9%)",
        "connectivity": "National Highway 53 (Nagpur-Amravati), Direct Samruddhi Expressway Junction",
        "tags": ["Samruddhi Feeder Node", "Warehousing Logistics", "Budget Land Investments"]
    },
    {
        "locality": "Koradi Road, Godhani & Mankapur",
        "city": "Nagpur",
        "state": "Maharashtra",
        "zone": "Nagpur North Outer",
        "category": "Outer Connected Suburb",
        "circle_rate": 3100,
        "circle_rate_plot": 2000,
        "market_rate_min": 3800,
        "market_rate_max": 6500,
        "market_rate_avg": 4900,
        "plot_rate_sqft": 2800,
        "plot_rate_guntha": 3049200,
        "duplex_avg_price": 7200000,
        "villa_avg_price": 11000000,
        "rental_yield": 4.1,
        "cagr_5y": 10.4,
        "infra_score": 8.7,
        "livability_score": 8.6,
        "lat": 21.2050,
        "lng": 79.0810,
        "sanction_authority": "NMC / NMRDA",
        "notable_projects": ["Koradi Temple Green Enclave", "Mankapur Sports City", "Godhani Heights"],
        "nhb_hpi_trend": "Infrastructure Expansion (QoQ +2.9%)",
        "connectivity": "Koradi 4-Lane Highway, Mankapur Indoor Stadium flyover",
        "tags": ["Koradi Thermal & Pilgrimage", "Sports Complex", "NMRDA Approved Layouts"]
    },
    {
        "locality": "Kamptee Road, Uppalwadi & Kanhan",
        "city": "Nagpur",
        "state": "Maharashtra",
        "zone": "Nagpur North-East Outer",
        "category": "Outer Satellite Town",
        "circle_rate": 2400,
        "circle_rate_plot": 1500,
        "market_rate_min": 2900,
        "market_rate_max": 5200,
        "market_rate_avg": 3800,
        "plot_rate_sqft": 1800,
        "plot_rate_guntha": 1960200,
        "duplex_avg_price": 5200000,
        "villa_avg_price": 7800000,
        "rental_yield": 4.3,
        "cagr_5y": 9.8,
        "infra_score": 8.3,
        "livability_score": 8.2,
        "lat": 21.2250,
        "lng": 79.1980,
        "sanction_authority": "NMRDA / Kamptee Municipal Council",
        "notable_projects": ["Dragon Palace Enclave", "Kanhan River Greens", "Kamptee Road Townships"],
        "nhb_hpi_trend": "Automotive & Freight Corridor (QoQ +2.5%)",
        "connectivity": "Nagpur Metro Phase 2 Extension Corridor, National Highway 44 (Jabalpur Road)",
        "tags": ["Dragon Palace Landmark", "Military Cantonment", "Affordable Housing & Plots"]
    },
    {
        "locality": "Umred Road, Dighori & Kharbi",
        "city": "Nagpur",
        "state": "Maharashtra",
        "zone": "Nagpur East Outer",
        "category": "Outer Suburb",
        "circle_rate": 2700,
        "circle_rate_plot": 1700,
        "market_rate_min": 3200,
        "market_rate_max": 5600,
        "market_rate_avg": 4100,
        "plot_rate_sqft": 2100,
        "plot_rate_guntha": 2286900,
        "duplex_avg_price": 5800000,
        "villa_avg_price": 8900000,
        "rental_yield": 4.4,
        "cagr_5y": 10.9,
        "infra_score": 8.2,
        "livability_score": 8.2,
        "lat": 21.1150,
        "lng": 79.1450,
        "sanction_authority": "NMRDA / NIT",
        "notable_projects": ["Dighori Vihar", "Umred Highway Farms", "Kharbi Smart City"],
        "nhb_hpi_trend": "Emerging Residential (QoQ +3.1%)",
        "connectivity": "Umred State Highway, Nagpur Outer Ring Road East Interchange",
        "tags": ["Fastest Plot Absorption", "Budget Duplex Homes", "Ring Road Connectivity"]
    },

    # =========================================================================
    # PUNE: MAIN CITY + PCMC + EXTENSIVE OUTER & INDUSTRIAL / IT BELTS
    # =========================================================================
    {
        "locality": "Kothrud, Karve Nagar & Deccan",
        "city": "Pune",
        "state": "Maharashtra",
        "zone": "Pune West Core",
        "category": "Main City",
        "circle_rate": 9500,
        "circle_rate_plot": 7800,
        "market_rate_min": 12500,
        "market_rate_max": 22000,
        "market_rate_avg": 15500,
        "plot_rate_sqft": 14500,
        "plot_rate_guntha": 15790500,
        "duplex_avg_price": 26000000,
        "villa_avg_price": 42000000,
        "rental_yield": 3.7,
        "cagr_5y": 9.6,
        "infra_score": 9.6,
        "livability_score": 9.7,
        "lat": 18.5074,
        "lng": 73.8077,
        "sanction_authority": "PMC",
        "notable_projects": ["Sobha Nesara", "Paranjape Schemes", "Gokhale Kothrud Heights"],
        "nhb_hpi_trend": "Cultural Heritage Core (QoQ +2.1%)",
        "connectivity": "Pune Metro Aqua Line (Vanaz & Ideal Colony), Chandani Chowk Flyover Junction",
        "tags": ["Cultural Heart", "Top Schools & Colleges", "High Status Residential"]
    },
    {
        "locality": "Koregaon Park, Kalyani Nagar & Boat Club Road",
        "city": "Pune",
        "state": "Maharashtra",
        "zone": "Pune Central-East",
        "category": "Main City Prime",
        "circle_rate": 11800,
        "circle_rate_plot": 9500,
        "market_rate_min": 15000,
        "market_rate_max": 28000,
        "market_rate_avg": 19500,
        "plot_rate_sqft": 18500,
        "plot_rate_guntha": 20146500,
        "duplex_avg_price": 35000000,
        "villa_avg_price": 65000000,
        "rental_yield": 3.5,
        "cagr_5y": 10.2,
        "infra_score": 9.7,
        "livability_score": 9.8,
        "lat": 18.5362,
        "lng": 73.8940,
        "sanction_authority": "PMC",
        "notable_projects": ["Trump Towers Pune", "Panchshil One North", "Marvel Waterfront"],
        "nhb_hpi_trend": "Ultra Luxury Pune (QoQ +2.5%)",
        "connectivity": "North Main Road, Pune Railway Station, Aga Khan Palace Bridge",
        "tags": ["Trump Towers", "Bungalows & Penthouses", "Nightlife & Fine Dining"]
    },
    {
        "locality": "Baner, Balewadi & Aundh",
        "city": "Pune",
        "state": "Maharashtra",
        "zone": "Pune West",
        "category": "Main City Prime",
        "circle_rate": 8200,
        "circle_rate_plot": 6500,
        "market_rate_min": 10500,
        "market_rate_max": 17500,
        "market_rate_avg": 13400,
        "plot_rate_sqft": 11500,
        "plot_rate_guntha": 12523500,
        "duplex_avg_price": 22000000,
        "villa_avg_price": 38000000,
        "rental_yield": 4.3,
        "cagr_5y": 12.2,
        "infra_score": 9.5,
        "livability_score": 9.4,
        "lat": 18.5590,
        "lng": 73.7868,
        "sanction_authority": "PMC",
        "notable_projects": ["Kasturi The Balmoral", "Supreme Estia", "VTP Hilife", "Rohan Leher"],
        "nhb_hpi_trend": "High Demand (QoQ +3.4%)",
        "connectivity": "Balewadi High Street, Mumbai-Bangalore Highway NH 48, Metro Corridor",
        "tags": ["Balewadi High Street", "Tech Executives Hub", "Premium Gated Communities"]
    },
    {
        "locality": "Hinjewadi (Phases 1-4), Marunji, Maan & Kasarsai",
        "city": "Pune",
        "state": "Maharashtra",
        "zone": "Pune West Outer",
        "category": "Outer IT Capital & Plots",
        "circle_rate": 5800,
        "circle_rate_plot": 3400,
        "market_rate_min": 7200,
        "market_rate_max": 12800,
        "market_rate_avg": 9400,
        "plot_rate_sqft": 3600,
        "plot_rate_guntha": 3920400, # ~₹39.2L per Guntha (Marunji/Maan NA plots)
        "duplex_avg_price": 12500000,
        "villa_avg_price": 19500000,
        "rental_yield": 4.9,
        "cagr_5y": 13.8,
        "infra_score": 9.2,
        "livability_score": 8.7,
        "lat": 18.5913,
        "lng": 73.7389,
        "sanction_authority": "PMRDA / MIDC",
        "notable_projects": ["Kolte Patil Life Republic", "Godrej 24", "Megapolis", "Paranjape Blue Ridge"],
        "nhb_hpi_trend": "Highest IT Tenant Demand (QoQ +3.9%)",
        "connectivity": "Pune Metro Line 3 (Hinjewadi-Shivajinagar), Mumbai-Pune Expressway Link Road",
        "tags": ["Rajiv Gandhi Infotech Park", "PMRDA Sanctioned Plots", "Massive High-Rise Townships"]
    },
    {
        "locality": "Wakad, Pimple Saudagar, Ravet & Punawale",
        "city": "Pune",
        "state": "Maharashtra",
        "zone": "PCMC",
        "category": "PCMC City & Outer Suburbs",
        "circle_rate": 6600,
        "circle_rate_plot": 4500,
        "market_rate_min": 7900,
        "market_rate_max": 13500,
        "market_rate_avg": 10200,
        "plot_rate_sqft": 6200,
        "plot_rate_guntha": 6751800,
        "duplex_avg_price": 14500000,
        "villa_avg_price": 22000000,
        "rental_yield": 4.5,
        "cagr_5y": 11.8,
        "infra_score": 9.1,
        "livability_score": 9.1,
        "lat": 18.5987,
        "lng": 73.7667,
        "sanction_authority": "PCMC / PMRDA",
        "notable_projects": ["VTP HiLife", "Kolte Patil Western Avenue", "Urban Skyline Ravet", "Pharande Spaces"],
        "nhb_hpi_trend": "High Volume Housing (QoQ +3.1%)",
        "connectivity": "Aundh-Ravet BRTS Road, Mumbai-Pune Bypass, Dange Chowk Flyover",
        "tags": ["Young Tech Demographic", "Expressway Gateway", "High Quality Schools"]
    },
    {
        "locality": "Moshi (Spine Road), Chakan MIDC & Alandi",
        "city": "Pune",
        "state": "Maharashtra",
        "zone": "PCMC / North Pune Outer",
        "category": "Outer Industrial & Auto Corridor",
        "circle_rate": 4200,
        "circle_rate_plot": 2500,
        "market_rate_min": 5200,
        "market_rate_max": 8900,
        "market_rate_avg": 6800,
        "plot_rate_sqft": 2900,
        "plot_rate_guntha": 3158100, # ~₹31.6L per Guntha
        "duplex_avg_price": 8500000,
        "villa_avg_price": 12500000,
        "rental_yield": 4.8,
        "cagr_5y": 14.1,
        "infra_score": 8.9,
        "livability_score": 8.5,
        "lat": 18.6750,
        "lng": 73.8450,
        "sanction_authority": "PCMC / PMRDA / MIDC",
        "notable_projects": ["Moshi High Street", "Pharande Woodsville", "Chakan Auto City Enclaves"],
        "nhb_hpi_trend": "Auto Cluster Growth (QoQ +4.1%)",
        "connectivity": "Nashik Phata to Khed Elevated Highway, Spine Road, Pune Ring Road Node",
        "tags": ["Pune International Exhibition Center (PIECC)", "Mercedes/VW/Bajaj Auto Hub", "Budget Plots & Duplexes"]
    },
    {
        "locality": "Kharadi (EON & WTC), Wagholi & Keshav Nagar",
        "city": "Pune",
        "state": "Maharashtra",
        "zone": "Pune East",
        "category": "East IT Hub & Suburbs",
        "circle_rate": 7400,
        "circle_rate_plot": 4800,
        "market_rate_min": 9200,
        "market_rate_max": 15800,
        "market_rate_avg": 11800,
        "plot_rate_sqft": 6500,
        "plot_rate_guntha": 7078500,
        "duplex_avg_price": 17500000,
        "villa_avg_price": 28000000,
        "rental_yield": 4.7,
        "cagr_5y": 12.6,
        "infra_score": 9.3,
        "livability_score": 9.1,
        "lat": 18.5515,
        "lng": 73.9349,
        "sanction_authority": "PMC / PMRDA",
        "notable_projects": ["Panchshil Eon Waterfront", "Gera World of Joy", "VTP Pegasus Wagholi", "Rohan Abhilasha"],
        "nhb_hpi_trend": "Strong Eastern Demand (QoQ +3.5%)",
        "connectivity": "EON Free Zone, World Trade Center Pune, Nagar Road Metro Phase",
        "tags": ["World Trade Center", "EON IT Park", "Wagholi PMRDA Plots"]
    },
    {
        "locality": "Bavdhan, Pashan, Sus & Pirangut (Lavasa Road)",
        "city": "Pune",
        "state": "Maharashtra",
        "zone": "Pune South-West Outer",
        "category": "Outer Scenic Valley & Villa Belts",
        "circle_rate": 6200,
        "circle_rate_plot": 3800,
        "market_rate_min": 7800,
        "market_rate_max": 13800,
        "market_rate_avg": 9800,
        "plot_rate_sqft": 4500,
        "plot_rate_guntha": 4900500,
        "duplex_avg_price": 14500000,
        "villa_avg_price": 26000000, # Scenic Hillside Villas
        "rental_yield": 4.2,
        "cagr_5y": 11.5,
        "infra_score": 9.0,
        "livability_score": 9.3,
        "lat": 18.5140,
        "lng": 73.7720,
        "sanction_authority": "PMC / PMRDA",
        "notable_projects": ["Shapoorji Pallonji Vanaha", "Puraniks Abitante", "Marvel Ganga Bavdhan"],
        "nhb_hpi_trend": "Nature & Hill View Living (QoQ +3.0%)",
        "connectivity": "Chandani Chowk Multilevel Flyover, Paud Road, Hinjewadi-Sus Link Road",
        "tags": ["Hill Station Vibe", "Vanaha Valley Township", "Luxury Bungalow & Plot Plots"]
    },
    {
        "locality": "Sinhagad Road, Narhe, Dhayari & Nanded City",
        "city": "Pune",
        "state": "Maharashtra",
        "zone": "Pune South",
        "category": "South Residential Hub",
        "circle_rate": 5600,
        "circle_rate_plot": 3500,
        "market_rate_min": 6800,
        "market_rate_max": 11200,
        "market_rate_avg": 8600,
        "plot_rate_sqft": 4200,
        "plot_rate_guntha": 4573800,
        "duplex_avg_price": 11500000,
        "villa_avg_price": 18500000,
        "rental_yield": 4.3,
        "cagr_5y": 10.6,
        "infra_score": 8.9,
        "livability_score": 8.9,
        "lat": 18.4720,
        "lng": 73.8180,
        "sanction_authority": "PMC",
        "notable_projects": ["Nanded City Mega Township", "Dhayari Heights", "Sinhagad Green Enclaves"],
        "nhb_hpi_trend": "Township Centric (QoQ +2.7%)",
        "connectivity": "Sinhagad Road Flyover, Mumbai-Bangalore Bypass, Khadakwasla Dam axis",
        "tags": ["Nanded City Pioneer", "Scenic Khadakwasla Environs", "Affordable Family Flats"]
    },

    # =========================================================================
    # MUMBAI MMR: MAIN CITY + THANE + NAVI MUMBAI + EXTENDED SATELLITES & COASTAL
    # =========================================================================
    {
        "locality": "Bandra West & BKC",
        "city": "Mumbai",
        "state": "Maharashtra",
        "zone": "Western Suburbs & BKC",
        "category": "Main City Prime",
        "circle_rate": 42000,
        "circle_rate_plot": 32000,
        "market_rate_min": 58000,
        "market_rate_max": 95000,
        "market_rate_avg": 72000,
        "plot_rate_sqft": 65000,
        "plot_rate_guntha": 70785000,
        "duplex_avg_price": 120000000, # ₹12 Cr+
        "villa_avg_price": 250000000, # ₹25 Cr+
        "rental_yield": 3.1,
        "cagr_5y": 9.8,
        "infra_score": 9.7,
        "livability_score": 9.5,
        "lat": 19.0596,
        "lng": 72.8295,
        "sanction_authority": "MCGM / MMRDA",
        "notable_projects": ["Rustomjee Seasons", "Supreme Stellar", "Ten BKC", "Signet Bandra"],
        "nhb_hpi_trend": "Top Tier India (QoQ +2.9%)",
        "connectivity": "Bandra-Worli Sea Link, Metro Line 3 (Aqua Line), SCLR",
        "tags": ["Billionaires & Bollywood", "Corporate Headquarters", "Sea Views"]
    },
    {
        "locality": "Worli, Lower Parel & Prabhadevi",
        "city": "Mumbai",
        "state": "Maharashtra",
        "zone": "South Mumbai",
        "category": "Main City Prime",
        "circle_rate": 38000,
        "circle_rate_plot": 28000,
        "market_rate_min": 48000,
        "market_rate_max": 92000,
        "market_rate_avg": 64000,
        "plot_rate_sqft": 58000,
        "plot_rate_guntha": 63162000,
        "duplex_avg_price": 95000000,
        "villa_avg_price": 180000000,
        "rental_yield": 3.2,
        "cagr_5y": 8.9,
        "infra_score": 9.8,
        "livability_score": 9.4,
        "lat": 19.0176,
        "lng": 72.8170,
        "sanction_authority": "MCGM",
        "notable_projects": ["Lodha World One", "Oberoi 360 West", "Piramal Mahalaxmi", "Lodha Park"],
        "nhb_hpi_trend": "Skyscraper Capital (QoQ +2.2%)",
        "connectivity": "Mumbai Coastal Road (Operational), BWSL, Metro Line 3",
        "tags": ["Skyscraper Row", "Coastal Road Interchange", "Luxury Sea Penthouses"]
    },
    {
        "locality": "Thane West (Ghodbunder Road, Majiwada & Pokhran)",
        "city": "Thane",
        "state": "Maharashtra",
        "zone": "Thane Prime",
        "category": "Thane City & Suburbs",
        "circle_rate": 9200,
        "circle_rate_plot": 6800,
        "market_rate_min": 11500,
        "market_rate_max": 21000,
        "market_rate_avg": 15200,
        "plot_rate_sqft": 12800,
        "plot_rate_guntha": 13939200,
        "duplex_avg_price": 24000000,
        "villa_avg_price": 38000000,
        "rental_yield": 4.1,
        "cagr_5y": 11.4,
        "infra_score": 9.1,
        "livability_score": 9.0,
        "lat": 19.2183,
        "lng": 72.9781,
        "sanction_authority": "TMC / MMRDA",
        "notable_projects": ["Rustomjee Urbania", "Lodha Amara", "Piramal Vaikunth", "Hiranandani Estate"],
        "nhb_hpi_trend": "High Demand MMR (QoQ +3.5%)",
        "connectivity": "Eastern Express Highway, Metro Line 4 & 5, Borivali-Thane Twin Tunnel",
        "tags": ["Mega Self-Contained Townships", "Borivali Twin Tunnel", "Lush Yeoor Hills"]
    },
    {
        "locality": "Kharghar, Panvel & Ulwe (Airport & MTHL Axis)",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "zone": "Navi Mumbai South",
        "category": "Navi Mumbai & Airport City",
        "circle_rate": 7800,
        "circle_rate_plot": 5200,
        "market_rate_min": 9200,
        "market_rate_max": 18500,
        "market_rate_avg": 12800,
        "plot_rate_sqft": 8500,
        "plot_rate_guntha": 9256500, # ~₹92.5L per Guntha (CIDCO Tripartite NA plots)
        "duplex_avg_price": 18500000,
        "villa_avg_price": 29000000,
        "rental_yield": 4.4,
        "cagr_5y": 14.8,
        "infra_score": 9.3,
        "livability_score": 9.1,
        "lat": 19.0473,
        "lng": 73.0699,
        "sanction_authority": "CIDCO / NMMC / PMC",
        "notable_projects": ["Hiranandani Fortune City", "Paradise Sai World City", "Godrej City Panvel", "Marathon Nexzone"],
        "nhb_hpi_trend": "Infrastructure Mega Boom (QoQ +4.5%)",
        "connectivity": "Navi Mumbai International Airport (NMIA), Atal Setu (MTHL), Navi Mumbai Metro Line 1",
        "tags": ["Atal Setu Direct Link", "International Airport", "CIDCO Sanctioned Plots", "Golf Course"]
    },
    {
        "locality": "Kalyan-Dombivli & Lodha Palava City",
        "city": "Kalyan",
        "state": "Maharashtra",
        "zone": "MMR Outer",
        "category": "Outer Satellite City",
        "circle_rate": 4800,
        "circle_rate_plot": 3100,
        "market_rate_min": 5800,
        "market_rate_max": 11000,
        "market_rate_avg": 7800,
        "plot_rate_sqft": 4200,
        "plot_rate_guntha": 4573800,
        "duplex_avg_price": 9500000,
        "villa_avg_price": 14500000,
        "rental_yield": 4.5,
        "cagr_5y": 10.2,
        "infra_score": 8.4,
        "livability_score": 8.3,
        "lat": 19.2437,
        "lng": 73.1355,
        "sanction_authority": "KDMC / MMRDA",
        "notable_projects": ["Runwal MyCity", "Lodha Palava Phase 1 & 2", "Regency Antilia", "Godrej Riviera"],
        "nhb_hpi_trend": "High Volume Affordable (QoQ +2.9%)",
        "connectivity": "Central Railway Junction, Metro Line 5 (Thane-Bhiwandi-Kalyan), Airoli-Katai Tunnel Road",
        "tags": ["First-Time Buyers", "Lodha Palava Smart City", "Airoli Tunnel Link"]
    },
    {
        "locality": "Mira Road, Bhayandar, Vasai & Virar",
        "city": "Mira-Bhayandar",
        "state": "Maharashtra",
        "zone": "North MMR Coastal",
        "category": "North MMR Suburbs",
        "circle_rate": 5800,
        "circle_rate_plot": 3800,
        "market_rate_min": 6800,
        "market_rate_max": 12500,
        "market_rate_avg": 8800,
        "plot_rate_sqft": 5500,
        "plot_rate_guntha": 5989500,
        "duplex_avg_price": 11000000,
        "villa_avg_price": 16500000,
        "rental_yield": 4.3,
        "cagr_5y": 9.8,
        "infra_score": 8.6,
        "livability_score": 8.5,
        "lat": 19.2812,
        "lng": 72.8561,
        "sanction_authority": "MBMC / VVCMC / MMRDA",
        "notable_projects": ["Kalpataru Srishti", "Rustomjee Global City Virar", "JP North Garden City"],
        "nhb_hpi_trend": "Metro Extension Surge (QoQ +3.0%)",
        "connectivity": "Western Railway Suburban Line, Metro Line 9 (Dahisar-Mira Bhayandar), Western Express Highway",
        "tags": ["Metro Line 9", "Rustomjee Mega City", "Coastal Living & Sea Breeze"]
    },
    {
        "locality": "Alibaug (Mandwa, Awas, Zirad & Coastal NA Plots)",
        "city": "Alibaug",
        "state": "Maharashtra",
        "zone": "Konkan Coast MMR",
        "category": "Coastal Luxury & Villa Plots",
        "circle_rate": 3500,
        "circle_rate_plot": 2800,
        "market_rate_min": 6500,
        "market_rate_max": 24000,
        "market_rate_avg": 12500,
        "plot_rate_sqft": 4800,
        "plot_rate_guntha": 5227200, # ~₹52.3L per Guntha (Collector Sanctioned NA plots)
        "duplex_avg_price": 19500000,
        "villa_avg_price": 45000000, # Luxury Coastal Villas
        "rental_yield": 6.2,
        "cagr_5y": 16.5,
        "infra_score": 8.8,
        "livability_score": 9.6,
        "lat": 18.6414,
        "lng": 72.8722,
        "sanction_authority": "Collector Raigad / CIDCO / MMRDA",
        "notable_projects": ["Awas Beach Enclaves", "Mandwa Speedboat Villas", "House of Abhinandan Lodha (HoABL)"],
        "nhb_hpi_trend": "Celebrity & Second Home Capital (QoQ +5.2%)",
        "connectivity": "Ro-Ro Ferry (Mandwa to Ferry Wharf Mumbai in 45 mins), Atal Setu (MTHL) to Chirle Link, Rewas Bridge",
        "tags": ["Hamptons of Mumbai", "Speedboat to Gateway of India", "High Short-Stay Rental Yield", "Luxury NA Plots"]
    },
    {
        "locality": "Karjat, Neral & Badlapur Foothills",
        "city": "Karjat",
        "state": "Maharashtra",
        "zone": "MMR Foothills",
        "category": "Weekend Homes & Farmhouse Plots",
        "circle_rate": 2200,
        "circle_rate_plot": 1400,
        "market_rate_min": 2800,
        "market_rate_max": 5800,
        "market_rate_avg": 3900,
        "plot_rate_sqft": 1650,
        "plot_rate_guntha": 1796850, # ~₹18L per Guntha
        "duplex_avg_price": 4800000,
        "villa_avg_price": 8500000,
        "rental_yield": 5.4,
        "cagr_5y": 13.2,
        "infra_score": 8.2,
        "livability_score": 8.9,
        "lat": 18.9100,
        "lng": 73.3280,
        "sanction_authority": "Collector Raigad / PMRDA corridor",
        "notable_projects": ["Godrej Golf Greens Karjat", "Wadhwa Wise City Panvel-Karjat", "Tata Value Homes"],
        "nhb_hpi_trend": "High Plot & Villa Demand (QoQ +3.8%)",
        "connectivity": "Panvel-Karjat Suburban Railway Double Track, Mumbai-Pune Expressway exit",
        "tags": ["Western Ghats Nature", "Sanctioned Farmhouse Plots", "Panvel-Karjat Railway Link"]
    },

    # =========================================================================
    # BANGALORE (BENGALURU): SILICON VALLEY OF INDIA & TECH CORRIDORS
    # =========================================================================
    {
        "locality": "Whitefield, ITPL & Kadugodi",
        "city": "Bangalore",
        "state": "Karnataka",
        "zone": "East Bangalore",
        "category": "Main Tech Hub",
        "circle_rate": 6200,
        "circle_rate_plot": 4800,
        "market_rate_min": 7800,
        "market_rate_max": 14500,
        "market_rate_avg": 10500,
        "plot_rate_sqft": 7500,
        "plot_rate_guntha": 8167500, # ~₹81.7L per Guntha (1 Guntha = 1089 sqft)
        "duplex_avg_price": 16500000,
        "villa_avg_price": 28000000,
        "rental_yield": 4.8,
        "cagr_5y": 13.8,
        "infra_score": 9.4,
        "livability_score": 9.2,
        "lat": 12.9698,
        "lng": 77.7499,
        "sanction_authority": "BDA / BMRDA",
        "notable_projects": ["Prestige Shantiniketan", "Godrej Splendour", "Sobha Windsor", "Brigade Woods"],
        "nhb_hpi_trend": "High Tech Demand (QoQ +4.2%)",
        "connectivity": "Namma Metro Purple Line (Whitefield Kadugodi), ITPL Main Rd, Outer Ring Road",
        "tags": ["ITPL Tech Hub", "Purple Line Metro", "High Rental Yield", "Gated Villa Townships"]
    },
    {
        "locality": "Sarjapur Road, Bellandur & ORR Axis",
        "city": "Bangalore",
        "state": "Karnataka",
        "zone": "South-East Bangalore",
        "category": "ORR Tech Corridor",
        "circle_rate": 6800,
        "circle_rate_plot": 5200,
        "market_rate_min": 8500,
        "market_rate_max": 16200,
        "market_rate_avg": 11800,
        "plot_rate_sqft": 8200,
        "plot_rate_guntha": 8929800,
        "duplex_avg_price": 18500000,
        "villa_avg_price": 32000000,
        "rental_yield": 4.9,
        "cagr_5y": 14.5,
        "infra_score": 9.3,
        "livability_score": 9.0,
        "lat": 12.9230,
        "lng": 77.6850,
        "sanction_authority": "BDA / BBMP",
        "notable_projects": ["Assetz Marq", "Prestige City Sarjapur", "Godrej Park Retreat"],
        "nhb_hpi_trend": "Top Rental ROI Belt (QoQ +4.5%)",
        "connectivity": "Outer Ring Road (ORR), Upcoming Blue Line Metro, Carmelaram Railway Station",
        "tags": ["ORR Tech Parks", "Prestige Smart City", "High Corporate Demand"]
    },
    {
        "locality": "Hebbal, Manyata Tech Park & Yelahanka",
        "city": "Bangalore",
        "state": "Karnataka",
        "zone": "North Bangalore",
        "category": "Airport Corridor & Tech Hub",
        "circle_rate": 7200,
        "circle_rate_plot": 5500,
        "market_rate_min": 9200,
        "market_rate_max": 18000,
        "market_rate_avg": 12600,
        "plot_rate_sqft": 8800,
        "plot_rate_guntha": 9583200,
        "duplex_avg_price": 21000000,
        "villa_avg_price": 36000000,
        "rental_yield": 4.6,
        "cagr_5y": 14.1,
        "infra_score": 9.5,
        "livability_score": 9.3,
        "lat": 13.0358,
        "lng": 77.5970,
        "sanction_authority": "BDA / BIAAPA",
        "notable_projects": ["L&T Raintree Boulevard", "Godrej Woodsman Estate", "Salarpuria Sattva Senorita"],
        "nhb_hpi_trend": "Airport Corridor Boom (QoQ +3.9%)",
        "connectivity": "Bellary Road (NH 44), Hebbal Flyover, Upcoming Blue Line Airport Metro",
        "tags": ["Manyata Embassy Business Park", "Kempegowda Airport Axis", "Luxury High-Rises"]
    },

    # =========================================================================
    # HYDERABAD: HIGH-GROWTH CAPITAL & CYBERABAD CORRIDOR
    # =========================================================================
    {
        "locality": "Gachibowli, Financial District & Kokapet (Neopolis)",
        "city": "Hyderabad",
        "state": "Telangana",
        "zone": "Cyberabad West",
        "category": "High-Density Commercial & Luxury",
        "circle_rate": 5800,
        "circle_rate_plot": 4600,
        "market_rate_min": 8500,
        "market_rate_max": 17500,
        "market_rate_avg": 12200,
        "plot_rate_sqft": 9500,
        "plot_rate_guntha": 10345500,
        "duplex_avg_price": 22500000,
        "villa_avg_price": 45000000,
        "rental_yield": 4.5,
        "cagr_5y": 15.8,
        "infra_score": 9.6,
        "livability_score": 9.4,
        "lat": 17.4401,
        "lng": 78.3489,
        "sanction_authority": "HMDA / TSIIC",
        "notable_projects": ["My Home Bhooja", "Aparna Zenon", "Rajapushpa Provincia", "Jayabheri The Peak"],
        "nhb_hpi_trend": "Neopolis Mega Boom (QoQ +5.1%)",
        "connectivity": "Neopolis Trumpet Flyover, Outer Ring Road (ORR), Raidurg Metro Station",
        "tags": ["Neopolis Kokapet", "Financial District IT", "Ultra-Luxury Skyscraper Living"]
    },
    {
        "locality": "Tellapur, Mokila & Shankarpalli (Western Villa Belt)",
        "city": "Hyderabad",
        "state": "Telangana",
        "zone": "West Hyderabad Outer",
        "category": "Villa & Residential Gated Townships",
        "circle_rate": 4200,
        "circle_rate_plot": 3200,
        "market_rate_min": 5800,
        "market_rate_max": 9800,
        "market_rate_avg": 7500,
        "plot_rate_sqft": 5200,
        "plot_rate_guntha": 5662800, # ~₹56.6L per Guntha
        "duplex_avg_price": 12500000,
        "villa_avg_price": 24000000,
        "rental_yield": 4.2,
        "cagr_5y": 14.8,
        "infra_score": 9.0,
        "livability_score": 9.1,
        "lat": 17.4800,
        "lng": 78.2650,
        "sanction_authority": "HMDA",
        "notable_projects": ["My Home Tridasa Tellapur", "Aparna Sarovar", "Fortune Green Homes Mokila"],
        "nhb_hpi_trend": "Gated Villa Destination (QoQ +4.4%)",
        "connectivity": "ORR Exit 2, MMTS Tellapur Station, 15 mins to Financial District",
        "tags": ["HMDA Approved Layouts", "Luxury Triplex Villas", "Fast Emerging Corridor"]
    },

    # =========================================================================
    # DELHI NCR: GURGAON, NOIDA & DELHI PRIME
    # =========================================================================
    {
        "locality": "Golf Course Road & DLF Phase 1-5",
        "city": "Delhi NCR",
        "state": "Delhi NCR",
        "zone": "Gurgaon Prime",
        "category": "Super Luxury & Corporate",
        "circle_rate": 14500,
        "circle_rate_plot": 11000,
        "market_rate_min": 22000,
        "market_rate_max": 55000,
        "market_rate_avg": 34000,
        "plot_rate_sqft": 28000,
        "plot_rate_guntha": 30492000,
        "duplex_avg_price": 65000000,
        "villa_avg_price": 150000000,
        "rental_yield": 3.8,
        "cagr_5y": 13.5,
        "infra_score": 9.7,
        "livability_score": 9.6,
        "lat": 28.4682,
        "lng": 77.0980,
        "sanction_authority": "GMDA / HSVP",
        "notable_projects": ["DLF The Camellias", "DLF The Aralias", "The Magnolias", "M3M Golfestate"],
        "nhb_hpi_trend": "Ultra Luxury Landmark (QoQ +4.6%)",
        "connectivity": "16-Lane Golf Course Road Expressway, Rapid Metro Gurgaon, Delhi Metro Yellow Line",
        "tags": ["Billionaires' Row Gurgaon", "Golf Course Views", "DLF Camellias Benchmark"]
    },
    {
        "locality": "Sector 150 & Noida-Greater Noida Expressway",
        "city": "Delhi NCR",
        "state": "Delhi NCR",
        "zone": "Noida Expressway",
        "category": "Green Sports City & Low Density",
        "circle_rate": 6200,
        "circle_rate_plot": 4800,
        "market_rate_min": 7800,
        "market_rate_max": 14500,
        "market_rate_avg": 10800,
        "plot_rate_sqft": 7800,
        "plot_rate_guntha": 8494200,
        "duplex_avg_price": 14500000,
        "villa_avg_price": 26000000,
        "rental_yield": 4.2,
        "cagr_5y": 14.1,
        "infra_score": 9.4,
        "livability_score": 9.2,
        "lat": 28.4410,
        "lng": 77.4980,
        "sanction_authority": "NOIDA Authority",
        "notable_projects": ["Godrej Palm Retreat", "Tata Eureka Park", "ATS Pious Orchards", "Ace Golfshire"],
        "nhb_hpi_trend": "Sports City Growth (QoQ +3.8%)",
        "connectivity": "Noida-Greater Noida Expressway, Aqua Line Metro (Sector 148 Station), FNG Expressway",
        "tags": ["Low Density Sports City", "70% Greenery", "Noida International Airport Jewar Axis"]
    },

    # =========================================================================
    # AHMEDABAD: GIFT CITY & PRIME WEST BELT
    # =========================================================================
    {
        "locality": "SG Highway, Bodakdev & Sindhu Bhavan Road",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "zone": "West Ahmedabad",
        "category": "Posh Residential & High Street",
        "circle_rate": 5400,
        "circle_rate_plot": 4100,
        "market_rate_min": 7200,
        "market_rate_max": 13800,
        "market_rate_avg": 9800,
        "plot_rate_sqft": 7500,
        "plot_rate_guntha": 8167500,
        "duplex_avg_price": 15500000,
        "villa_avg_price": 28000000,
        "rental_yield": 4.1,
        "cagr_5y": 11.8,
        "infra_score": 9.3,
        "livability_score": 9.3,
        "lat": 23.0450,
        "lng": 72.5180,
        "sanction_authority": "AMC / AUDA",
        "notable_projects": ["Goyal & Co Orchid", "Adani Shantigram", "Sun South Park", "Shivalik Highstreet"],
        "nhb_hpi_trend": "High Net Worth Corridor (QoQ +3.4%)",
        "connectivity": "Sarkhej-Gandhinagar (SG) Highway, Sindhu Bhavan Flyover, Ahmedabad Metro Line 1",
        "tags": ["High Street Cafes & Dining", "Palladium Mall", "Luxury Penthouse Enclaves"]
    },

    # =========================================================================
    # CHENNAI: OMR TECH CORRIDOR & COASTAL LIVING
    # =========================================================================
    {
        "locality": "OMR (Old Mahabalipuram Road), Sholinganallur & Perungudi",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "zone": "South Chennai IT Corridor",
        "category": "IT Express Corridor",
        "circle_rate": 5800,
        "circle_rate_plot": 4200,
        "market_rate_min": 6800,
        "market_rate_max": 13200,
        "market_rate_avg": 9200,
        "plot_rate_sqft": 6800,
        "plot_rate_guntha": 7405200,
        "duplex_avg_price": 13500000,
        "villa_avg_price": 24000000,
        "rental_yield": 4.7,
        "cagr_5y": 11.2,
        "infra_score": 9.1,
        "livability_score": 9.0,
        "lat": 12.9010,
        "lng": 80.2280,
        "sanction_authority": "CMDA",
        "notable_projects": ["Hiranandani Parks OMR", "Casagrand Zenith", "Appaswamy Platina"],
        "nhb_hpi_trend": "IT Workforce Demand (QoQ +3.2%)",
        "connectivity": "OMR IT Expressway, Upcoming Metro Phase 2 (Line 3), ECR Link",
        "tags": ["TCS/Infosys Tech Hub", "Metro Phase 2", "Beach Proximity"]
    },

    # =========================================================================
    # KOLKATA: SALT LAKE IT SECTOR V & NEW TOWN ACTION AREA
    # =========================================================================
    {
        "locality": "New Town (Action Area 1-3) & Salt Lake Sector V",
        "city": "Kolkata",
        "state": "West Bengal",
        "zone": "East Kolkata",
        "category": "Planned Smart City & IT Hub",
        "circle_rate": 4800,
        "circle_rate_plot": 3400,
        "market_rate_min": 5800,
        "market_rate_max": 10500,
        "market_rate_avg": 7800,
        "plot_rate_sqft": 5400,
        "plot_rate_guntha": 5880600,
        "duplex_avg_price": 11500000,
        "villa_avg_price": 19500000,
        "rental_yield": 4.5,
        "cagr_5y": 10.5,
        "infra_score": 9.2,
        "livability_score": 9.2,
        "lat": 22.5868,
        "lng": 88.4754,
        "sanction_authority": "WBHIDCO / NKDA",
        "notable_projects": ["Mani Casadona", "PS One10", "Unitech Uniworld City", "Ambuja Utalika"],
        "nhb_hpi_trend": "Smart City Expansion (QoQ +3.0%)",
        "connectivity": "Major Arterial Road (MAR), Green Line Metro (Sector V to Howrah), Kolkata Airport (10 mins)",
        "tags": ["HIDCO Planned Town", "Eco Park Environs", "IT Sector V Tech Campus"]
    },

    # =========================================================================
    # JAIPUR: PINK CITY HERITAGE & MODERN TECH CORRIDORS
    # =========================================================================
    {
        "locality": "Malviya Nagar, Jagatpura & Airport Axis",
        "city": "Jaipur",
        "state": "Rajasthan",
        "zone": "South Jaipur",
        "category": "Posh Residential & Educational",
        "circle_rate": 4500,
        "circle_rate_plot": 3200,
        "market_rate_min": 5400,
        "market_rate_max": 9800,
        "market_rate_avg": 7200,
        "plot_rate_sqft": 4800,
        "plot_rate_guntha": 5227200,
        "duplex_avg_price": 9500000,
        "villa_avg_price": 17500000,
        "rental_yield": 4.2,
        "cagr_5y": 12.4,
        "infra_score": 9.1,
        "livability_score": 9.2,
        "lat": 26.8530,
        "lng": 75.8050,
        "sanction_authority": "JDA (Jaipur Development Authority)",
        "notable_projects": ["Mahima Panorama", "Ashiana Greenwood", "UDB Skydeck"],
        "nhb_hpi_trend": "Airport & Education Boom (QoQ +3.6%)",
        "connectivity": "Jawahar Lal Nehru (JLN) Marg, Tonk Road, Jaipur International Airport (5 mins)",
        "tags": ["World Trade Park (WTP)", "MNIT Campus", "Posh Family Neighborhoods"]
    },

    # =========================================================================
    # LUCKNOW: GOMTI NAGAR EXTENSION & SHAHEED PATH
    # =========================================================================
    {
        "locality": "Gomti Nagar Extension, Shaheed Path & Golf City",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "zone": "East Lucknow",
        "category": "Modern Planned High-Rise Hub",
        "circle_rate": 4200,
        "circle_rate_plot": 2900,
        "market_rate_min": 5200,
        "market_rate_max": 9200,
        "market_rate_avg": 6900,
        "plot_rate_sqft": 4500,
        "plot_rate_guntha": 4900500,
        "duplex_avg_price": 8900000,
        "villa_avg_price": 16500000,
        "rental_yield": 4.6,
        "cagr_5y": 13.6,
        "infra_score": 9.2,
        "livability_score": 9.1,
        "lat": 26.8250,
        "lng": 81.0150,
        "sanction_authority": "LDA (Lucknow Development Authority)",
        "notable_projects": ["Rishita Manhattan", "Eldeco Latitude 27", "Omaxe Hazratganj", "Shalimar Grand"],
        "nhb_hpi_trend": "Infrastructure Super Growth (QoQ +4.0%)",
        "connectivity": "Amar Shaheed Path, Purvanchal Expressway Link, Ekana International Cricket Stadium",
        "tags": ["Lulu Mall Axis", "Ekana Stadium", "Medanta Super Speciality", "LDA Approved Townships"]
    },

    # =========================================================================
    # GOA: NORTH & SOUTH GOA LUXURY VILLAS & BEACH BELT
    # =========================================================================
    {
        "locality": "North Goa Coastal (Anjuna, Assagao, Siolim & Parra)",
        "city": "Goa",
        "state": "Goa",
        "zone": "North Goa Coastal",
        "category": "Super Luxury Holiday Villas & NA Plots",
        "circle_rate": 4800,
        "circle_rate_plot": 3800,
        "market_rate_min": 8500,
        "market_rate_max": 28000,
        "market_rate_avg": 14500,
        "plot_rate_sqft": 7800,
        "plot_rate_guntha": 8494200, # ~₹84.9L per Guntha (Sanctioned Settlement / NA Plots)
        "duplex_avg_price": 22000000,
        "villa_avg_price": 55000000, # Luxury Portuguese Villas
        "rental_yield": 7.2,
        "cagr_5y": 18.2,
        "infra_score": 9.1,
        "livability_score": 9.7,
        "lat": 15.5890,
        "lng": 73.7650,
        "sanction_authority": "Town & Country Planning (TCP Goa) / Collector NA",
        "notable_projects": ["Vianaar La Mer", "Isprava Estate Villas", "Acron Waterfront", "Veera Eminence"],
        "nhb_hpi_trend": "Highest Holiday Rental Yield in India (QoQ +5.8%)",
        "connectivity": "Manohar International Airport (MOPA) Highway in 30 mins, Coastal Highway, Panaji Atal Setu",
        "tags": ["Luxury Boutique Villas", "Celebrity Holiday Homes", "High AirBnB Yields", "Settlement Sanctioned Land"]
    }
]
